#!/bin/bash

if [ -z "$1" ]
then
  echo "You need to pick a board name. e.g., ./build \"Cool JS Crew\""
  exit 1
fi

node -pe "JSON.stringify({boardName: \"$1\"})" > name.json
npm run generate-keys
npm run build
npm run inline
